language: ruby
rvm:
- 2.4.3
- 2.3.6
- 2.3.1
bundler_args: "--retry 5"
script:
- bin/rake db:migrate RAILS_ENV=test
- bin/rake
deploy:
  provider: heroku
  app: can-i-buy
  api_key:
    secure: sG/GMzokam6y4k8MIfOaJ7g4ZkxHAK5KRziqnnxSDb3wj2zpLkGVmxxu7Y8XunBtBEcmxjfu/YDZrVzZ6AlrLibuFbNd0e70IsALDarzmM8WKvD5BmsMyfeGjQGBIjMACRF+1Ihoe6pRu4LJJbOKPokMgiLpoRBYvTtU/5PbvHV2Rpi9Z5R0NgyoC+J/Ufna0uC3QKqQzHZydJ+03JSVtu3w11IiK5ILw/5sO3ofiCfx9r+ltapCiizSJQlQZgK86zxdeBSiUeaJu1l4swm5aooQYJDwR8mgTccnJLq86QAcMXEXguWCKO7iqWxPp+Y/BO4RLxnOiwEGHf/UjTbAlE03iTNGHfBX0UUKS6Cey5JRJ/+Gxfk1XHwgohqyiMxAQONMR+uuonJXSuHLT5A+HBHHMYSt8LzpV6PB+Wwbo+f22HTD46it9NFyxmHApKhv7VwsE4S6FxfJlaN/qwpEyr0Kv6RHj2m6w/p+VXC5oj1txJR3F515Tl2mQMuj3E4qjllrJB0syUIMcmIGS4GtjG9PUaCfU9LRN+P+ZfxJYe2UdfwrJPT4Ah8vIWuG3pZYdU28IaTXV/kUb4wNiSFSez7MN/oLHsNFUOZvycKtnpq1kLKN1Xlzu4RnfgcQt+d5vOTXezpWQPnh2vAQ+WSRC7rlozoyJl4sr9usGzFMAYs=
  strategy: git
  on:
    branch: master
    rvm: 2.3.1
