language: ruby
rvm:
- 2.4.3
- 2.3.6
- 2.3.1
bundler_args: "--retry 5"
script:
- bin/rake db:migrate RAILS_ENV=test
- bin/rake
deploy:
  provider: heroku
  app: can-i-buy
  api_key:
    secure: g9m8jbvHBivAMJ+aKV6NHqkKzYwuTkFS0TQCfIuJNceauUJcgsHIzcG77+Cp5MSSykamV36wSoDr/8aEPAZigwLVhS/JpFyxqcg5s/LfrC/5jVlsDgNjow7Scz17Gxh0nTo5HA6JMyzuouNuWupRweMtxu+2qya0NdodUORQaGb3biGyYt/KUBHurr7JDGgUywZnxiuqcrKFFcwsyjM3ztzJhdbs8YEeIzCo/FY5J11VXft0hHlO18wK3xheKLZaF3QLgcOlzj90NBMWjxXgJz7vMw3hApSvnt7xu0FlrdZyCs1A2KAf47Cyqy5Xn3gk5sB4wKZb986m56EJRJdh7Zw5WlC5VJM69ExA7mDjnKBkOLad90tRxt4/kF4Jm2XTm3swmJ1juVhfkLDd2sVjEhltvaq82+x7VU4OK3rQrFheuM24cRf7SCBijGJJMzVjTJPr9QOKkfaU2VoTGlPf6//C3XMFe7k6dXmdt4rAWwinuUcFGuSoL+jaC+iyKZF0ffubIpt+oOxeIEw4V3A4rtuiTYIZ9CYzxKo66W99tFfzCDtdPQxOBCRIXCZuj24kHNXjCGVgSxm/1IzSmX06LqLWNQIGWJ4xBw5UN3gaKI8mxoIRjTLlUZySVNxZLy0MXcYvN+oZD5m+zf36SypZ+MfanXlmgAjvN7KACNjTvRs=
  strategy: git
  on:
    branch: master
    rvm: 2.3.1
